eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:6781/eureka/

server:
  port: 8901

spring:
  application:
    name: zuul

#配置路由，将/api-feign/**路由到feign服务
#例如：http://localhost:8901/api-feign/hello?name=kl
zuul:
  routes:

   feign:
    path: /api-feign/**
    serviceId: feign

   client:
    path: /api-client/**
    serviceId: client


