server:
  port: 8901

eureka:
  client:
    eureka-server-u-r-l-context: http:localhost:8761/eureka/
#将访问地址/api-feign/**路由到feign服务
#将访问地址/api-client/**路由到client服务
zuul:
  routes:
    feign:
      path: /api-feign/**
      serviceId: feign
    client:
      path: /api-client/**
      serviceId: client

spring:
  application:
    name: zuul

