#eureka端口
server:
  port: 8761
#IP地址
eureka:
  instance:
    hostname: 127.0.0.1
  client:
  #下面两行为false，说明为Eureka Server
    register-with-eureka: false
    fetch-registry: false
    #访问地址
    eureka-server-u-r-l-context:  http://${eureka.instance.hostname}:${server.port}/eureka/